# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
name: Build and deploy JAR app to Azure Web App - texs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          
      - name: Build with Maven
        run: mvn clean install -DskipTests
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F7958E0C38814A1DA041869DD368465C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A15E7A2D0D934670B56BA474D234F970 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_768531990D4D4A56849F4AC7E3CEFE43 }}
          
      - name: Stop Azure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp stop --name texs --resource-group YOUR_RESOURCE_GROUP
            
      - name: Clean Web App Directory
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'texs'
          slot-name: 'Production'
          clean: true
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'texs'
          slot-name: 'Production'
          package: '*.jar'
          
      - name: Start Azure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp start --name texs --resource-group YOUR_RESOURCE_GROUP
